package model;

import java.time.Duration;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Person implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;
	private int age;
	private Address address;
	private List<PracticeLogEntry> practiceLogEntries;

	public Person() {
		practiceLogEntries = new ArrayList<PracticeLogEntry>();
	}
	
	public Person(String name, int age, Address address) {
		this.name = name;
		this.age = age;
		this.address = address;
		
		practiceLogEntries = new ArrayList<PracticeLogEntry>();
	}
	
	public Person(String name, int age, String street, String city, String state, String zip, String country) {
		this.name = name;
		this.age = age;
		this.address = new Address(street, city, state, zip, country);
		
		practiceLogEntries = new ArrayList<PracticeLogEntry>();
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public Address getAddress() {
		return address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public List<PracticeLogEntry> getPracticeLogEntries() {
		return practiceLogEntries;
	}

	public void setPracticeLogEntries(List<PracticeLogEntry> practiceLogEntries) {
		this.practiceLogEntries = practiceLogEntries;
	}

}